### PR TITLE
Fixing empty exception message in Circuit Breaker

### PR DESCRIPTION
**Pull request by WojcikMike**
cc: @bording

### CODE REVIEW

**Comment by WojcikMike** [comment]
@Particular/transport-maintainers please review and merge

**Comment by SeanFeldman** [comment]
I really think there should be a @Particular/rabbitmq-maintainers. General @Particular/transport-maintainers doesn't really fit the bill here :)

**Comment by bording** [comment]
> I really think there should be a @Particular/rabbitmq-maintainers.

@SeanFeldman That's the plan, I don't think it's been done yet though.

**Comment by andreasohlund** [comment]
I've raised a proposal to create a rabbit specific maintainers group - https://github.com/Particular/PlatformDevelopment/issues/716

**Pull request merged**
