### PR TITLE
update to beta1

### PR DESCRIPTION
**Pull request by SimonCropp**
not sure how to fix the iwant usages

Connects to https://github.com/Particular/PlatformDevelopment/issues/719

### CODE REVIEW

**Comment by andreasohlund** [comment]
Connected this one to https://github.com/Particular/PlatformDevelopment/issues/719

**Comment by andreasohlund** [comment]
Since parent issue is flagged v6 I'm removing the label from this one

**Comment by andreasohlund** [comment]
@kbaley @colin-higgins @distantcam @boblangley this was broken by   https://github.com/Particular/NServiceBus/issues/3342 can someone sort out the `IWantToRunAtAtStartAndStop` usages to get this one green?

Are there other downstreams that was was missed in the POA for https://github.com/Particular/NServiceBus/issues/3342 ?

cc @Particular/nservicebus-maintainers 
cc @Particular/platform-dev-squad

**Comment by colin-higgins** [comment]
If no one else is taking this, I will pick it up.

@kbaley @colin-higgins @distantcam @boblangley

**Comment by colin-higgins** [comment]
Rebased on develop

**Comment by colin-higgins** [comment]
@Particular/transport-maintainers @SimonCropp @bording 

Ready for review

**Comment by bording** [comment]
Made a couple minor tweaks, but otherwise this is good to go. I'm going to go ahead and merge this since everything is broken otherwise (unstables removed from myget).

**Pull request merged**
