### PR TITLE
add mailmap

### PR DESCRIPTION
**Pull request by adamralph**
Before:

```
C:\code\Particular\NServiceBus.RabbitMQ> git shortlog -sne
   170  Brandon Ording <bording@gmail.com>
   110  John Simons <john.simons@nservicebus.com>
   103  Andreas Öhlund <andreas.ohlund@particular.net>
    43  Simon Cropp <simon.cropp@gmail.com>
    20  Adam Ralph <adam@adamralph.com>
    18  andreasohlund <andreasohlund2@gmail.com>
    13  Andreas Öhlund <andreasohlund2@gmail.com>
    11  Mike Minutillo <michael.minutillo@gmail.com>
    10  John Simons <john@thesimonshouse.com>
    10  SzymonPobiega <szymon.pobiega@gmail.com>
     5  andreasohlund <andreas.ohlund@particular.net>
     4  Itamar Syn-Hershko <itamar@code972.com>
     3  Michał Wójcik <wojcik.mike@gmail.com>
     3  Particular Bot <engineering@particular.net>
     3  indualagarsamy <indu.alagarsamy@gmail.com>
     3  sfarmar <s.farmar@gmail.com>
     2  Fawad Halim <fawad@fawad.net>
     2  danielmarbach <daniel.marbach@particular.net>
     1  Cameron MacFarland <distantcam@gmail.com>
     1  Daniel Marbach <daniel.marbach@particular.net>
     1  Greg Bielleman <greg.bielleman@gmail.com>
     1  Panu Peuramäki <peuramaki@iki.fi>
     1  Scooletz <scooletz@gmail.com>
     1  Scott Meyer <scott.meyer@firehost.com>
     1  Szymon Kulec <scooletz@gmail.com>
     1  Tim Bussmann <tim.bussmann@particular.net>
     1  Tomasz Masternak <tomasz.masternak@particular.net>
     1  Yves Goeleven <yves@goeleven.com>
     1  louis-pierre.beaumont <louis-pierre.beaumont@ver-mac.com>
```

After:
```
C:\code\Particular\NServiceBus.RabbitMQ> git shortlog -sne
   170  Brandon Ording <bording@gmail.com>
   139  Andreas Öhlund <andreas.ohlund@particular.net>
   120  John Simons <john.simons@nservicebus.com>
    43  Simon Cropp <simon.cropp@gmail.com>
    21  Adam Ralph <adam@adamralph.com>
    11  Mike Minutillo <michael.minutillo@gmail.com>
    10  SzymonPobiega <szymon.pobiega@gmail.com>
     4  Itamar Syn-Hershko <itamar@code972.com>
     3  Michał Wójcik <wojcik.mike@gmail.com>
     3  Particular Bot <engineering@particular.net>
     3  danielmarbach <daniel.marbach@particular.net>
     3  indualagarsamy <indu.alagarsamy@gmail.com>
     3  sfarmar <s.farmar@gmail.com>
     2  Fawad Halim <fawad@fawad.net>
     2  Szymon Kulec <scooletz@gmail.com>
     1  Cameron MacFarland <distantcam@gmail.com>
     1  Greg Bielleman <greg.bielleman@gmail.com>
     1  Panu Peuramäki <peuramaki@iki.fi>
     1  Scott Meyer <scott.meyer@firehost.com>
     1  Tim Bussmann <tim.bussmann@particular.net>
     1  Tomasz Masternak <tomasz.masternak@particular.net>
     1  Yves Goeleven <yves@goeleven.com>
     1  louis-pierre.beaumont <louis-pierre.beaumont@ver-mac.com>
```

Once we prove this works here, we can push this up to https://github.com/Particular/RepoStandards

### CODE REVIEW

**Comment by andreasohlund** [comment]
Like it!

**Comment by bording** [comment]
Looks like `Scooletz <scooletz@gmail.com>` and `Szymon Kulec <scooletz@gmail.com>` should be combined also.

Overall, I'm somewhat mixed on adding this. On one hand, it does make the shortlog more accurate, so that's cool.

On the other hand, it's one more file that has to be maintained. AFAIK GitHub itself doesn't use it, and already does the combining [here](https://github.com/Particular/NServiceBus.RabbitMQ/graphs/contributors) based on the email addresses people have linked to their accounts.

Given that it's not really a huge burden to maintain the file, I don't see the harm in adding it.

**Comment by SimonCropp** [comment]
What is the value of shortlog when github exposes this information?

**Comment by adamralph** [comment]
shortlog is useful when seeing who's worked on a branch, e.g.

image

GitHub does this combining on email addresses but that relies on the user settings of the contributor rather than being controlled in source. Also, it's sometimes possible for commits to have no verifiable email address, e.g. "devnull@localhost".

shortlog also works offline.

**Comment by adamralph** [comment]
@bording good spot regarding Szymon Kulec. I've amended the commit to add an entry for him.

**Comment by bording** [comment]
Given that this isn't a huge maintenance cost, and does have some benefits, makes sense to me to merge this.

**Pull request merged**
