### PR TITLE
Fix tests for new CI process

### PR DESCRIPTION
**Pull request by dbelcham**
Added `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` to testing csproj files to enable testing on TC

Remove dot from env var for Linux.

### CODE REVIEW

**Comment by adamralph** [comment]
I've updated the title and description in light of the second commit.

**Comment by adamralph** [comment]
Marking as WIP until we get all the new build configs working.

**Comment by adamralph** [comment]
Clearing the review request for now. @dbelcham @kbaley please request a review when appropriate.

**Comment by adamralph** [comment]
Hmmm.. OK, I can't remove the review request. ¯\_(ツ)_/¯

**Comment by bording** [comment]
This is now ready to be merged.

**Pull request merged**
