### PR TITLE
Core v6 update

### PR DESCRIPTION
**Pull request by johnsimons**
Upgrade transport to use NServiceBus v6.
Connects to Particular/NServiceBus#3125

Still left to do:
- [x] Always use ack, autoack can cause message loss, see #122
- [x] Implement callbacks
- [x] Decide whether SecondaryReceiveSettings still needed with current MessagePump: not relevant anymore.
- [x] Remove PrefetchCount and use PushRuntimeSettings.MaxConcurrency for BasicQos()
- [x] Read Circuit breaker settings from config
- [x] `RepeatedFailuresOverTimeCircuitBreaker.Failure()` not actually being called anywhere
- [x] DequeueTimeout setting not used, remove the config option
- [x] Remove HostConfiguration and just use Host
- [ ] Test that inflight messages are ok to use taskid for dictionary keys
- [ ] DirectRoutingTopology "broken": should use multiple keys, not one, can't handle multiple interfaces, see #123
- [ ] Update docs
- [ ] Update samples Particular/docs.particular.net#1011
- [ ] Clean up xml doc comments

### CODE REVIEW

**Comment by andreasohlund** [comment]
>Decide whether PrefetchCount config setting should be removed (and use maxconcurrency instead) or keep to override

Isn't PrefectCount = 1 the correct default? (see #100 for full discussion)

**Comment by bording** [comment]
> Isn't PrefectCount = 1 the correct default? (see #100 for full discussion)

With the way the previous version is implemented, setting the PrefetchCount to 1 is likely the right thing ti do (though some perf testing I've been doing shows that a higher value is still beneficial).

However, with the new message pump design, that is no longer true. It uses a single channel/consumer and the PrefetchCount is set to the MaxConcurrency level, so you can control the value through that single setting. Allowing end users to independently set the PrefetchCount doesn't really make sense in the current design.

**Comment by andreasohlund** [comment]
@bording thanks for clarifying!  Can you update and close #100 ?

**Comment by bording** [comment]
While testing some things, I discovered that SendOnly endpoints aren't calling `RabbitMQTransport.Dispose()` when the endpoint is stopped, so the process won't quit properly.

I've filed Particular/NServiceBus#3392 with the info I discovered on the reasons behind it.

**Comment by bording** [comment]
@johnsimons Looking at how DequeueTimeout was used in the previous version, we definitely don't need it anymore, so I removed it. I also made the parser throw an exception if it finds a configuration string that still has it. 

The error message I have there is pretty basic, and could probably use some more tweaking.

Thoughts?

**Comment by bording** [comment]
While this isn't 100% finished yet, the vast majority of the work has been done, and all the acceptance tests are passing.

I'm going to go ahead and merge this to develop, and will continue working on it from there, opening up separate issues for the remaining work items.

**Pull request merged**
