### PR TITLE
Creation of exchanges should honor durability settings

### LINKED ISSUE #49: Creation of exchanges should honor durability settings
When creating exchanges we should look at

https://github.com/Particular/NServiceBus/blob/def31db15977a6017737f134c15d1698edff97e0/src/NServiceBus.Core/Settings/DurableMessagesConfig.cs#L40

Eg:

https://github.com/Particular/NServiceBus.RabbitMQ/blob/develop/src/NServiceBus.RabbitMQ/Routing/ConventionalRoutingTopology.cs#L121

We're already doing when creating queues

### PR DESCRIPTION
**Pull request by johnsimons**
Fixes #49

### CODE REVIEW

**Comment by johnsimons** [comment]
@andreasohlund please review.
Any ideas on how to test this?

**Comment by andreasohlund** [comment]
@johnsimons seems like there are broken tests

**Comment by johnsimons** [comment]
there must be something wrong with build server

**Comment by johnsimons** [comment]
looks good

**Pull request merged**
