### PR TITLE
Upgrade to NServiceBus 6.0.0-beta0006

### LINKED ISSUE #174: Upgrade to NServiceBus 6.0.0-beta0006
This beta contains breaking changes wrt recoverability and routing.

Connects to https://github.com/Particular/V6Launch/issues/69
Connects to https://github.com/Particular/NServiceBus/pull/3956

### PR DESCRIPTION
**Pull request by adamralph**
Fixes #174

### CODE REVIEW

**Comment by adamralph** [comment]
I upgraded to a local build of NSB release-6.0.0 @ 07979cbde16864bba505f7aa42712e88791126f6

 - commented out uses of ScaleOutExtensions.ScaleOut until I know what to use instead
 - passed a naive stub in RabbitMqContext for the ErrorContext Func, not sure if it's appropriate
 - removed When_disabling_durable_messages_on_durable_transport and When_using_non_durable_messages_on_durable_only_transport until Particular/NServiceBus#3917 is merged

/cc @Particular/nservicebus-maintainers

**Comment by danielmarbach** [comment]
@bording @timbussmann can you guys answer this question?

> commented out uses of ScaleOutExtensions.ScaleOut until I know what to use instead

**Comment by bording** [comment]
> commented out uses of ScaleOutExtensions.ScaleOut until I know what to use instead

The replacement for that is `EndpointConfiguration.MakeInstanceUniquelyAddressable`. There isn't currently an obsoleted implementation of `ScaleOutSettings.InstanceDiscriminator` because that method was added in V6, so I wasn't thinking that we needed to keep it around.

`InstanceDiscriminator` was the only non-deprecated method still on `ScaleOutSettings`, so it and the `ScaleOut` extension method are now completely deprecated.

@Particular/nservicebus-maintainers Is "did it exist in V5" still the correct test for whether we need an obsolete member?

**Comment by timbussmann** [comment]
> @Particular/nservicebus-maintainers Is "did it exist in V5" still the correct test for whether we need an obsolete member?

I'd say yes

**Comment by adamralph** [comment]
Thanks @bording.

> The replacement for that is EndpointConfiguration.MakeInstanceUniquelyAddressable.

Should we change the obsolete message for `ScaleOutExtensions.ScaleOut` to tell us this?

**Comment by danielmarbach** [comment]
@adamralph If I recall correctly V5 didn't have these extensions. So it is not an obsoletion in the classical v5 vs v6 sense. But I could be wrong

**Comment by adamralph** [comment]
@danielmarbach the comment above by @bording implies that it was in V5. @bording can you confirm?

**Comment by danielmarbach** [comment]
I understood @bording comment differently

**Comment by adamralph** [comment]
@danielmarbach you're correct. I interpreted it incorrectly.

I'm still confused though. Was `ScaleOutExtensions.ScaleOut` added in v6? If so, why is there an obsolete at all?

**Comment by adamralph** [comment]
OK, I think I get it now:

* `ScaleExtensions.ScaleOut` was in V5, and returned `ScaleOutSettings`.
* `ScaleOutSettings.InstanceDiscriminator` was added in V6.
* Since then, both types and their methods were obsoleted, with the exception of `ScaleOutSettings.InstanceDiscriminator` which was removed, since it was new in V6.

Basically, what @bording said. :wink:

**Comment by adamralph** [comment]
PR updated and all tests passing locally.

**Comment by adamralph** [comment]
I've separated the changes out to three commits:

1. a raw upgrade from core beta4 to beta6
2. the minimum changes required to make the solution compile again
3. the new recoverability implementation

When the beta6 nupkg is released, it should be possible to update the PR like so:
1. amend the first commit (including changing the commit message to "red: upgrade to NSB 6.0.0-beta0006")
2. cherry pick the compilation commit, fixing any conflicts and adding any more required changes (hopefully none) and amend the commit
3. cherry pick the recoverability commit (hopefully no changes required)

**Comment by adamralph** [comment]
OK, now 4 commits:

1. a raw upgrade from core beta4 to beta6
2. the minimum changes required to make the solution compile again
3. tweaks to the source code tests to suit our context
4. the new recoverability implementation

**Comment by adamralph** [comment]
Superseded by https://github.com/Particular/NServiceBus.RabbitMQ/pull/190

**Pull request closed without merging**
