### PR TITLE
[WIP] csx build script spike

### PR DESCRIPTION
**Pull request by adamralph**
connects to #220

### CODE REVIEW

**Comment by adamralph** [comment]
Unfortunately it seems like VS Intellisense doesn't respect `#r` in a csx file. Raised https://github.com/dotnet/roslyn/issues/13856

**Comment by adamralph** [comment]
I wanted to split out the boiler plate for running and writing tasks into two separate csx files, and bring them into build.csx using `#load` but sadly VS Intellisense doesn't support `#load`. Raised https://github.com/dotnet/roslyn/issues/13888

Also raised https://github.com/dotnet/roslyn/issues/13886 and https://github.com/dotnet/roslyn/issues/13887 for other csx Intellisense woes. Generally it seems to be rather unfinished and buggy.

**Comment by adamralph** [comment]
Closing spike.

**Comment by filipw** [comment]
use VS Code 😄

**Comment by adamralph** [comment]
👍 I've been having much better results with VS Code recently. The C# script support really seems to be going places.

**Comment by filipw** [comment]
great. the upcoming release will have "go to metadata" support from CSX.
Also all other general C# work (like i.e .https://github.com/OmniSharp/omnisharp-roslyn/pull/840) is now automatically available in CSX too.

**Pull request closed without merging**
