### PR TITLE
Fixed usage of callback receiver header

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* Moved reading incoming header to behavior
 * Moved adding our own header to behavior
 * Removed forward callback header behavior

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@johnsimons @mikeminutillo can you review? If it is fine, I'll cherry pick the commit to hotfix branch(es)

**Comment by SzymonPobiega** [comment]
Attempts to fix #105

**Comment by johnsimons** [comment]
It looks good.
So just to confirm, by using pipeline behaviors, we are not applying outgoing headers to uses of `ISendMessages` directly ?

**Comment by johnsimons** [comment]
Merged in https://github.com/Particular/NServiceBus.RabbitMQ/commit/934bfcca9f05d882d8ccdca623524454fb9347c9

**Pull request closed without merging**
