### PR TITLE
[WIP] Update to core 1228

### PR DESCRIPTION
**Pull request by andreasohlund**
cc @bording

### CODE REVIEW

**Comment by andreasohlund** [comment]
@SzymonPobiega please review

**Comment by andreasohlund** [comment]
@bording seems like the same amount of tests failed so most likely this didn't break anything

**Comment by andreasohlund** [comment]
Crap, seems like the acceptance tests doesn't stop properly with this change (had to kill 2 consecutive builds)

**Comment by bording** [comment]
I've rebased this onto the newly rebased release-4.0 branch.

I believe I've seen the test-hanging behavior locally on release-4.0 too, so I don't think this is new to this branch.

I'm going to go ahead and merge this.

**Pull request merged**
