### PR TITLE
Splitting message converter into header converter and default messageid strategy

### PR DESCRIPTION
**Pull request by danielmarbach**
For #186 is was spelunking in the code and saw that the message converter could be made static. One lead to another and I split out the different responsibilities of that class into header converter and default messageid strategy. 

I also removed LINQ for the ValuesToString method

Hope you like it.

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/rabbitmq-transport-maintainers please review

**Comment by danielmarbach** [comment]
Does https://github.com/Particular/NServiceBus.RabbitMQ/pull/188 superseed this?

**Comment by bording** [comment]
> Does #188 superseed this?

Not necessarily, since we could call the new converter bits introduced here from the newly refactored message pump as well.

I'm not yet sure what all we might want to take from this PR. At the very least, I want to grab the revised `ValuesToString` method. Removing LINQ usage from that was something I wanted to do but hadn't gotten to yet, so definitely :+1: on that.

**Comment by adamralph** [comment]
#188 has been merged. The changes in there are unrelated to those here (in spite of the conflict).

I agree with @bording in that the one change we can take from this immediately is the revised `ValuesToString` method.

@danielmarbach would you have time to isolate that change in another PR?

**Comment by danielmarbach** [comment]
@bording feel free to copy over what you need / want and close this PR

**Comment by adamralph** [comment]
The new `ValueToString` method has been pulled out into #223.

**Comment by adamralph** [comment]
Closing, so we can delete the release-4.0.0 branch. The PR branch will still be available.

**Pull request closed without merging**
